# Generated by Django 3.0.3 on 2021-02-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('HOUSING', 'Housing'), ('COMM_GIVE', 'Community Giveaways'), ('MENTAL_HEALTH', 'Mental Health'), ('INFO', 'Info Sessions/Webinars'), ('EVENTS', 'Events'), ('OTHER', 'Other')], default='OTHER', max_length=20, null=True)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('flyer', models.URLField(blank=True, null=True)),
                ('flyer_id', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('zoom', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('latitude', models.FloatField(blank=True, max_length=30, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=30, null=True)),
                ('resource', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource')),
            ],
        ),
    ]
