# Generated by Django 3.0.3 on 2021-03-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210210_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='flyer_id',
            new_name='flyerId',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='zoom',
            new_name='meetingLink',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='time',
        ),
        migrations.AddField(
            model_name='resource',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='isRecurring',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
