# Generated by Django 3.0.3 on 2021-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210319_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(blank=True, choices=[('FOOD', 'Food'), ('HOUSING', 'Housing'), ('COMM_GIVE', 'Community Giveaways'), ('MENTAL_HEALTH', 'Mental Health'), ('INFO', 'Info Sessions/Webinars'), ('EVENTS', 'Events'), ('WIFI', 'Free Wifi'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
