# Generated by Django 3.0.3 on 2021-02-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210205_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='resource',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
    ]
