# Generated by Django 3.0.3 on 2021-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210331_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='flyerId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='resource',
            name='organization',
            field=models.CharField(max_length=70),
        ),
    ]
