# Generated by Django 3.0.3 on 2021-04-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210326_0132'),
        ('api', '0009_auto_20210401_1348'),
    ]

    operations = [
    ]
